# Site settings
author: Phillip DiPhillipo
title: Coding Diaries 
header-img: img/home-bg.png
email: diphillipophillip@gmail.com
copyright_name: Phillip DiPhillipo
description: > # this means to ignore newlines until "baseurl:"
  Accumulating thoughts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  diphillipophillip

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
